### PR TITLE
Research Page changes

### PR DESCRIPTION
**Pull request by AkshayTeja**
-> Title section for research page has been updated, with an added waves effect, more content would be needed for description

### CODE REVIEW

**Comment by AkshayTeja** [comment]
New changes 
-> Wave layout has been customised , to make the text pop up 
-> Crafting new tech section removed as stated by Arpit
-> New phase 3 added, as asked by Arpit
More changes i'll do after today's meeting with Arpit

**Review by Abhijeetbyte — COMMENTED** [review]
This appears to be impressive

**Comment by AkshayTeja** [comment]
New changes
-> Research page heading section made to look better, with better colors and white text
-> Current challenges section looks more light weight now
-> Phase 3 content added in pilot studies section
-> Patents, publications section modified to look less bulky

**Comment by AkshayTeja** [comment]
New changes
-> Shadow added to phase section
->Better border added patents,publications section

**Comment by AkshayTeja** [comment]
New changes 
-> Research page, wave section updated to include key areas, as suggested by Arpit
-> Everything else in research page is sorted, only images to be added and links
-> Hero section of products page has been added, rest of the page i'll update soon
-> **Only in Navbar of products page, i have added a Corporate section as suggested by Arpit, so if that works, add it to other pages as well**

**Comment by Abhijeetbyte** [comment]
So far it looks good, but the AOS animation is delayed in the research page

**Pull request merged**
