### PR TITLE
Further Changes To About Us Page

### PR DESCRIPTION
**Pull request by AkshayTeja**
Changes since last PR:
-> Navigation with numbers at bottom of about us page has been made hidden for sm screens because i felt it is not needed in mobiles
-> Scroll to top button has been added that is completely responsive, changes color over hover and directs to top as soon as it is clicked
This is a better option for navigating smaller screens

If you like the above 2 changes, they can be added to all pages

### CODE REVIEW

**Comment by AkshayTeja** [comment]
-> Awards & Recognition section of About Us page has been updated, i've added card like elements that look visually better and without the blue background that was present before for the images

**Comment by AkshayTeja** [comment]
-> News articles section has been made to look neater and responsive
-> Same with Reports & Resources section
-> Tooltips (Show Info upon hover) has been added for the navigation at bottom of page, this gives a better idea for users about what they are going to click and where the page is headed to
**Above change can be added to all pages if it works for you**

 **This concludes changes to About us page, except for some data additions in reports and news articles**
 If any other changes are needed, let me know

**Comment by Abhijeetbyte** [comment]
Merge conflict, due to outdated about.html ( cause, concurrent commits ) :

 Here are the main updates:

* The bottom navigation bar is now hidden on small screens, which greatly enhances the user experience on mobile devices. This improvement will be replicated across other pages.
* A scroll-to-top button with a subtle animation has been added, significantly improving navigation.
* The newly added card-like elements for the Awarded and Recognition sections are visually superior and add a professional touch.
* Minor improvements in the Reports & Resources and News Articles sections have been made, specifically related to margins and title font sizes.
* The tooltip feature has been deemed unnecessary, as the bottom navigation bar is only enabled on medium to large screens where the top navigation bar, displaying page names, is also enabled.

I have directly applied these code sections to the main codebase.

Thank you for your valuable contributions and attention to detail. For future reference, please ensure to check your code on a responsive small screen, either using a physical smartphone or Google Dev Tools (mobile screen template). This practice provides a better sense of the design before finalizing the source code. The objective is to optimize styling and space usage, especially on small-width screens, to avoid excessive vertical space occupation or excessive scrolling.

Please make sure to sync your working repository after this PR cancellation to prevent any future merge conflicts.

@AkshayTeja

**Comment by AkshayTeja** [comment]
Alright, thank you

**Pull request closed without merging**
