### PR TITLE
Changes To Home Page

### PR DESCRIPTION
**Pull request by AkshayTeja**
-> In the Readme, the techstack has been updated to include javascript as well
-> Patents section has been combined with what we do section, giving a better look along with minor changes, making it responsive and better looking

### CODE REVIEW

**Comment by AkshayTeja** [comment]
-> Buttons have been changed to arrows with hover effect, in our work section
-> News and events section has been removed, and one latest news article section has been added at end of page for viewers to navigate through and visit the site, i have included the same link for latest news

If these changes are accepted, then this concludes the changes required for home page

**Comment by AkshayTeja** [comment]
-> The learn more buttons in our work section have been edited, font has been made smaller and it has been aligned center to look better
-> The latest news section has been changed, i have added ping animation to bring more attention to the section and have made it responsive

**Comment by Abhijeetbyte** [comment]
I appreciate the effort and attention to detail put into these enhancements. Your contributions significantly improve the look and functionality of our homepage. Additionally, there are some minor changes required from my side that I will address after this PR is merged. Thank you for your valuable work!

@AkshayTeja 



</br>


## Changelog Summary


1. Tech Stack Update:

* Updated the Readme to include JavaScript.

 2. Patents Section:

* Combined with the "What We Do" section for a more streamlined and responsive design.

3. Button Redesign:
* Replaced buttons with arrows and added a hover effect in the "Our Work" section.

4. News and Events Section:
* Removed the "News and Events" section.
* Added a "Latest News" article section at the end of the page with a link to the latest news.

5. Learn More Buttons:
* Edited "Learn More" buttons in the "Our Work" section.
* Made the font smaller and centered for a cleaner look.

6. Latest News Section:
* Added a ping animation for better visibility and made the section responsive.

**Comment by AkshayTeja** [comment]
Great, let me know once you have added the minor changes from your side, i will sync code and continue

**Pull request merged**
