### PR TITLE
New Responsive Navbar Added

### PR DESCRIPTION
**Pull request by AkshayTeja**
I have added a new navbar that is completely responsive and have experimented with color palette, here's how it looks:

image

image

### CODE REVIEW

**Comment by Abhijeetbyte** [comment]
Preview needed for changes :

https://github.com/AkshayTeja/Navmarg-research-and-innovation.github.io/settings/pages

Go to this setting in your repository, and deploy a GitHub page ( so, without downloading and executing source code locally, we can see your changes dynamically ) 

[Learn more](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)

Additionally, target the [development](https://github.com/Navmarg-Research-and-Innovation/Navmarg-research-and-innovation.github.io/tree/development) branch instead of the [main](https://github.com/Navmarg-Research-and-Innovation/Navmarg-research-and-innovation.github.io/tree/main) branch when sending Pull Requests

**Comment by AkshayTeja** [comment]
Ok my forked website is live you can check it out at 
https://akshayteja.github.io/Navmarg-research-and-innovation.github.io/

And i will target development branch from the next pull request as i cannot do it for current one

And you can see i have changed the title section (top section) of home page where i have added logos along with minor changes to navbar like transform upon hover

**Comment by Abhijeetbyte** [comment]
Review:

Thank you for your effort on this update! Here are a few thoughts and suggestions that might help refine the work further.

Logos are a key part of the header section. Placing them inside the main body banner does not have the best visual impact. If it weren't necessary, the navbar wouldn't be there in the first place; that's why it's below it.

It seems you've added a large number of template/standard module files (+301,340 lines) for a relatively small amount of actual new content (200 lines). This is not good for project maintainability and focused structure.

The website follows a **one-page** model designed for quick load times and future **maintainability**. Maintaining this structure is crucial.

I would recommend changing your workflow to **focus** more on the main body section of pages, especially pages 3-4. Enhancements here could really make a difference.

Reviewing the website structure (as outlined in README.md) against other modern websites in the same domain could provide valuable insights and inspire improvements.

Your dedication is evident, and with a bit more focus on these areas, you can achieve even better outcomes.

**Comment by AkshayTeja** [comment]
The files i had added were node modules, which was necessary for me to get tailwind intellisense via iniatilizing tailwind.

Anyhow the navbar can stay as it is, and i will focus on pages 3-4

**Pull request closed without merging**
